name = "linkedin-auto-post-scheduler"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Create a KV namespace in Cloudflare, then set id here:
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "55234bc19b484796be45860efcdad919"

[[kv_namespaces]]
binding = "IDEMPOTENCY_KV"
id = "1f84bd04a90947509aec170482032e56"